# UV configuration file
# Switch to official PyPI if Tsinghua mirror has issues

[pip]
# Use official PyPI
index-url = "https://pypi.org/simple"

# Alternative: Use Aliyun mirror (usually more stable in China)
# index-url = "https://mirrors.aliyun.com/pypi/simple/"

# Alternative: Use 163 mirror
# index-url = "https://mirrors.163.com/pypi/simple/"
